# Generated by Django 5.2 on 2025-04-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='has_adapted_toilet',
            new_name='adapted_toilets',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='has_ramp',
            new_name='ramps',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='has_tactile_elements',
            new_name='tactile_elements',
        ),
        migrations.RemoveField(
            model_name='location',
            name='address',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='location',
            name='description',
        ),
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='location',
            name='visual_impairment_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='wheelchair_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='wide_entrance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
