# Generated by Django 5.2 on 2025-04-13 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_has_adapted_toilet_location_adapted_toilets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='image_url',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
